services:
  postgres:
    image: postgres:16-alpine
    container_name: odin-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: odin
    ports:
      - "5432:5432"
    volumes:
      - odin-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: odin-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  odin-postgres-data:
